#!/bin/bash
NINSTALLER=${NINSTALLER:-yes}

# Install standard packages
sed -i 's/main/main universe/' /etc/apt/sources.list

apt-get update

export DEBIAN_FRONTEND=noninteractive

while read line; do
	apt-get -q -y install $line
done <<<$(cat pkglist)

# geert's ninstaller
if [ "$NINSTALLER" = "yes" ]; then
	# Python-pip... yeah fsck
	apt-get -q -y install python3-pip
	# now we're twice as big :-(
	pushd /root
	# We want the world in here
	rm -rf openvcloud_installer
	git clone https://github.com/0-complexity/openvcloud_installer.git
	[ $? -ne 0 ] && echo "Couldn't clone ninstaller repo" && exit 1
	mkdir ninstaller
	cp openvcloud_installer/scripts/install/* ninstaller/
	# get pip requirements
	cd ninstaller
	pip3 install --no-cache-dir -r requirements.txt
	rm -rf openvcloud_installer
	popd
fi

# 911 booted devices are accessible as root over ssh
sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

# configure networking
# no Ufuktu stuff
cat <<EOF >/etc/systemd/network/en.network
[Match]
Name=en*
[Network]
DHCP=yes
EOF
systemctl enable systemd-networkd
systemctl disable networking

# give it a sensible hostname
echo "boot911" >/etc/hostname
echo "127.0.0.1 boot911" >>/etc/hosts
echo "::1 boot911" >>/etc/hosts

# get resolving working
systemctl enable systemd-resolved

apt-get clean

useradd -Gsudo -m -s /bin/bash -c "GreenITGlobe User" gig

echo "root:rooter" | chpasswd
echo "gig:rooter" | chpasswd

mkdir /root/tools &>/dev/null
mv /Install /init-chroot /CtrlInstall /root/tools
chmod 755 /root/tools/init-chroot
chmod 755 /root/tools/Install
# add Geert's requirements for 'ninstaller'

# Run Installer
#
cat <<EOF >/etc/systemd/system/rc-local.service
[Unit]
Description=/etc/rc.local Compatibility
ConditionPathExists=/etc/rc.local

[Service]
Type=idle
ExecStart=/etc/rc.local
Standard{Output,Error}=journal+console
TimeoutSec=0
StandardOutput=tty
RemainAfterExit=yes
SysVStartPriority=99

[Install]
WantedBy=multi-user.target
EOF

systemctl enable rc-local

# Don't clear console
[ ! -d /etc/systemd/system/getty@.service.d ] && mkdir /etc/systemd/system/getty@.service.d
cat >/etc/systemd/system/getty@.service.d/noclear.conf <<EOF
[Service]
TTYVTDisallocate=no
EOF

# /etc/rc.local starts /root/tools/CtrlInstall

cat <<EOF >/etc/rc.local
#!/bin/bash
eval \$( cat /proc/cmdline )
if [ "\${install}" = "" ] ; then
	# do nothing
	:
else
	cd /root/tools
	./CtrlInstall > Installog
fi
EOF

# executable

chmod 755 /etc/rc.local
