#!/bin/bash
KVER=4.13.0-31-generic
# Install standard packages

# get a proper apt config
cat << EOF >/etc/apt/sources.list
deb http://nl.archive.ubuntu.com/ubuntu xenial main
deb http://nl.archive.ubuntu.com/ubuntu xenial universe
deb http://nl.archive.ubuntu.com/ubuntu xenial multiverse
deb http://nl.archive.ubuntu.com/ubuntu xenial-updates main
deb http://nl.archive.ubuntu.com/ubuntu xenial-updates universe
deb http://nl.archive.ubuntu.com/ubuntu xenial-updates multiverse
EOF

apt-get update
apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade


export DEBIAN_FRONTEND=noninteractive

while read line; do
	apt-get -q -y install $line
done <<<$(cat ubupkglist)

# add kernel
apt-get -q -y install linux-image-${KVER} linux-image-extra-${KVER} linux-headers-${KVER} linux-tools-${KVER}

# remove autoinstalled ssh keys
rm /etc/ssh/*key*

#prepare for authorized_keys
mkdir /root/.ssh

# need to be accessible as root (wtf)
sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

# give it a sensible hostname
echo "baseimage" >/etc/hostname
echo "127.0.0.1 baseimage" >>/etc/hosts
echo "::1 baseimage" >>/etc/hosts

# get resolving working
systemctl enable systemd-resolved

apt-get clean

useradd -Gsudo -m -s /bin/bash -c "GreenITGlobe User" gig

echo "gig:R00t3R" | chpasswd

# Don't clear console
[ ! -d /etc/systemd/system/getty@.service.d ] && mkdir /etc/systemd/system/getty@.service.d
cat >/etc/systemd/system/getty@.service.d/noclear.conf <<EOF
[Service]
TTYVTDisallocate=no
EOF

apt-get -y clean

