#!/bin/bash

# Install standard packages
sed -i 's/main/main universe/' /etc/apt/sources.list

apt-get update

export DEBIAN_FRONTEND=noninteractive

while read line; do
	apt-get -q -y install $line
done <<<$(cat ubupkglist)

# need to be accessible as root (wtf)
sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config

# give it a sensible hostname
echo "baseimage" >/etc/hostname
echo "127.0.0.1 baseimage" >>/etc/hosts
echo "::1 baseimage" >>/etc/hosts

# get resolving working
systemctl enable systemd-resolved

apt-get clean

useradd -Gsudo -m -s /bin/bash -c "GreenITGlobe User" gig

echo "gig:R00t3R" | chpasswd

# Don't clear console
[ ! -d /etc/systemd/system/getty@.service.d ] && mkdir /etc/systemd/system/getty@.service.d
cat >/etc/systemd/system/getty@.service.d/noclear.conf <<EOF
[Service]
TTYVTDisallocate=no
EOF

