#!/bin/bash
# cleanup
sudo rm -f binaries/*

# build the docker image, not much is needed, so we build it every time
docker rmi 911builder:latest
docker build . -t 911builder:latest

# build it, you'll find the build result in ./binaries
docker run --privileged --rm \
	-v $(pwd):/911builder 911builder:latest
	# -v $(pwd)/binaries:/binaries \

# that's all folks
# https://www.youtube.com/watch?v=b9434BoGkNQ
