#!/bin/bash

DESTFILE=${1:-/911builder/GIGINSTALLER.iso}

image=ubuimage-16.04.3.tgz
# basically, create a bootable iso
#   - vmlinuz
#   - ramfs
#   - ubuntu image
#   - Installer
# the ISO needs to have Label


# ok, on with it
mkdir binaries/isolinux
cp /usr/lib/ISOLINUX/* binaries/isolinux/
cp /usr/lib/syslinux/modules/bios/* binaries/isolinux/



# Isolinux boot config

cat << EOF > binaries/isolinux/isolinux.cfg
DEFAULT vesamenu.c32
PROMPT 0

MENU TITLE GreenITGlobe Controller installer -or- 911

LABEL 911
  MENU LABEL ^start 911boot
  KERNEL /vmlinuz
  INITRD /ramfs
LABEL 911 (without networking)
  MENU LABEL ^start 911boot no network
  KERNEL /vmlinuz ip=no
  INITRD /ramfs
LABEL ONE
  MENU LABEL ^Install Controller 1 (one)
  KERNEL /vmlinuz
  INITRD /ramfs
  APPEND install=ctrl-01 ip=no
LABEL TWO
  MENU LABEL ^Install Controller 2 (two)
  KERNEL /vmlinuz
  INITRD /ramfs
  APPEND install=ctrl-02 ip=no
LABEL THREE
  MENU LABEL ^Install Controller 3 (three)
  KERNEL /vmlinuz
  INITRD /ramfs
  APPEND install=ctrl-03 ip=no

DISPLAY menu.txt
TIMEOUT 300
EOF

# get files from Geert
cp -rav etc binaries
mkdir -p binaries/teleport/
wget "https://get.gravitational.com/teleport-v3.0.0-linux-amd64-bin.tar.gz" -O binaries/teleport/teleport.tar.gz

# create the ISO
cd binaries
genisoimage -r -V GIGINSTALL -cache-inodes -J -l -b isolinux/isolinux.bin \
	-c isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
	-boot-info-table -o ${DESTFILE} .
cd ..
# give it also a bootblock for starting from USB
isohybrid ${DESTFILE}
