#!/bin/bash

DESTFILE=${1:-GIGINSTALLER.iso}

site=http://lede.gig.tech
image=ubuntu-16.04.3-20171130.tgz
# basically, create a bootable iso
#   - vmlinuz
#   - ramfs
#   - ubuntu image
#   - Installer
# the ISO needs to have Label

# get the image
if [ ! -f binaries/${image} ] ; then
    wget --no-verbose ${site}/${image} -O binaries/${image}
fi

# ok, on with it
mkdir binaries/isolinux
cp /usr/lib/ISOLINUX/* binaries/isolinux/
cp /usr/lib/syslinux/modules/bios/* binaries/isolinux/



# Isolinux boot config

cat << EOF > binaries/isolinux/isolinux.cfg
DEFAULT vesamenu.c32
PROMPT 0

MENU TITLE GreenITGlobe Controller installer -or- 911

LABEL 911
  MENU LABEL ^start 911boot
  KERNEL /vmlinuz
  INITRD /ramfs
LABEL ONE
  MENU LABEL ^Install Controller 1 (one)
  KERNEL /vmlinuz
  INITRD /ramfs
  APPEND install=ctrl-01 ip=no
LABEL TWO
  MENU LABEL ^Install Controller 2 (two)
  KERNEL /vmlinuz
  INITRD /ramfs
  APPEND install=ctrl-02 ip=no
LABEL THREE
  MENU LABEL ^Install Controller 3 (three)
  KERNEL /vmlinuz
  INITRD /ramfs
  APPEND install=ctrl-03 ip=no

DISPLAY menu.txt
TIMEOUT 300
EOF

# create teststuff
# mkdir binaries/etc -p
# for LSB in {1..3} ; do
# 	cat << EOF > binaries/etc/ctrl0${LSB}.conf
# function create_dirs() {
#     mkdir -p /var/ovc/billing
#     mkdir -p /var/ovc/influx
#     mkdir -p /var/ovc/mongodb
#     mkdir -p /var/ovc/pxeboot
#     mkdir -p /var/ovc/0-access/index
# }
#
# HOSTNAME=be-loc-4-ctrl-0${LSB}
# DOMAIN=be-g8-4
# MASK=24
# MGMTVLAN=2311
# STORVLAN=2315
# PUBIP=10.101.109.20${LSB}
# PUBMASK=16
# PUBGW=10.101.0.${LSB}
# PUBVLAN=2312
# MGMTIP=10.109.2.${LSB}
# STORIP=10.109.3.${LSB}
# UNTAGIP=10.109.1.${LSB}
# EOF
# done

# get files from Geert
cp -rav etc binaries


# create the ISO
cd binaries
genisoimage -r -V GIGINSTALL -cache-inodes -J -l -b isolinux/isolinux.bin \
	-c isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
	-boot-info-table -o ${DESTFILE} .
cd ..
# give it also a bootblock for starting from USB
isohybrid ${DESTFILE}
