#!/bin/bash
trap "exit" INT
set -x

KVER=4.13.0-19-generic

# when running in a docker, we're root (no sudo)
SUDO="sudo "
[ $(awk -F/ '$2 == "docker"' /proc/self/cgroup | wc -l) -ne 0 ] && SUDO=""

DISTRO=xenial

if [ ! -d uburoot ] ; then
	# if the dir exists, we assume that part is already done
	# Otherwise:
	mkdir uburoot
	${SUDO} debootstrap --arch=amd64 ${DISTRO} uburoot  http://nl.archive.ubuntu.com/ubuntu/
fi

${SUDO} cp init-chroot ubupkglist adaptubuimage root
${SUDO} chroot root chmod +x adaptubuimage
${SUDO} chroot root /adaptubuimage

# image is built, tar it up
cd uburoot
${SUDO} tar  --numeric-owner -cf - . | pigz -c > ../binaries/ubuimage-16.04.3.tgz






