#!/bin/bash
# create workdir
KVER=4.13.0-19-generic
SUDO=""
[ $(awk -F/ '$2 == "docker"' /proc/self/cgroup) -ne 0 ] && SUDO="sudo "

source initramfs-tools/initramfs.conf

if [ ! -d root ] ; then
	# if the dir exists, we assume that part is already done
	# Otherwise:
	mkdir root
	${SUDO} debootstrap --arch=amd64 ${DISTRO} root
	# add packages
	${SUDO} cp ays-chroot pkglist adaptdistro root
	${SUDO} chroot root chmod +x adaptdistro
	${SUDO} chroot root /adaptdistro
fi

# build initramfs with running kernel modules
[ ! -d ./bin ] && mkdir bin
	
${SUDO} mkinitramfs -d initramfs-tools/ -o bin/ramfs ${KVER}
${SUDO} cp /boot/vmlinuz-${KVER} bin/vmlinuz
${SUDO} chown $(whoami):$(whoami) bin/*


