#!/bin/bash
# create workdir

set -x

KVER=4.13.0-19-generic

# when running in a docker, we're root (no sudo)
SUDO="sudo "
[ $(awk -F/ '$2 == "docker"' /proc/self/cgroup | wc -l) -ne 0 ] && SUDO=""

source initramfs-tools/initramfs.conf

if [ ! -d root ] ; then
	# if the dir exists, we assume that part is already done
	# Otherwise:
	mkdir root
	${SUDO} debootstrap --arch=amd64 ${DISTRO} root
	# add packages
fi

${SUDO} cp init-chroot pkglist adaptdistro CtrlInstall root
${SUDO} chroot root chmod +x adaptdistro
${SUDO} chroot root /adaptdistro

# build initramfs with running kernel modules

${SUDO} mkinitramfs -d initramfs-tools/ -o ../binaries/ramfs ${KVER}
${SUDO} cp /boot/vmlinuz-${KVER} ../binaries/vmlinuz
${SUDO} chown $(whoami):$(whoami) ../binaries/*


