#!/bin/sh
set -e

PREREQS="cryptsetup"
case $1 in
	prereqs) echo "${PREREQS}"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

##
copy_exec /bin/mount /bin
copy_exec /usr/bin/sha512sum /bin
copy_exec /bin/bash /bin
copy_exec /usr/bin/ipmitool /bin
copy_exec /usr/bin/wget /bin

manual_add_modules overlay
manual_add_modules dm_mod
manual_add_modules dm_crypt
manual_add_modules squashfs
# this is '||' only in case this module isn't built
manual_add_modules aesni_intel || true

# make squashfs from root
mksquashfs /home/gig/911builder/root ${DESTDIR}/root.sqfs -progress -comp lz4



# vi: ts=4 noexpandtab
